# Generated by Django 3.1.4 on 2020-12-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Host name')),
                ('webserver', models.IntegerField(choices=[(1, 'Apache'), (2, 'NGINX')], verbose_name='Webserver')),
            ],
        ),
    ]
